services:
  client:
    platform: linux/x86_64
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: kpi-client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - ./client/.env.dev
    develop:
      watch:
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/pnpm-lock.yaml

  server:
    platform: linux/x86_64
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: kpi-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5050:5050"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - ./server/config/.env.dev
    develop:
      watch:
        - action: rebuild
          path: ./server/package.json
        - action: rebuild
          path: ./server/pnpm-lock.yaml

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reporteria
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  db-init:
    platform: linux/x86_64
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: kpi-db-init
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./server/config/.env.dev
    volumes:
      - ./server/migrations:/app/migrations
    environment:
      SEED_ENV: /app/config/.env.dev
    command: ["sh", "-c", "pnpm run db:generate && pnpm run db:push --force && pnpm run seed:base && pnpm run seed:demo"]
    restart: "no"

volumes:
  redis:
    driver: local
  mysql:
    driver: local
